'use client';

import './globals.css';
import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import ClientNavbar from '@/components/navigation/ClientNavbar';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


interface ClientLayoutProps {
    children: React.ReactNode
}
const ClientLayout: React.FC<ClientLayoutProps> = ({children}) => {


    return (
      <html lang="en" className={inter.className}>
        <body className={montserrat.className}>
        <ClientNavbar address={"New York, USA"} />
           {children}
        </body>
      </html>
    );
}

export default ClientLayout