import './globals.css';
import type { Metadata } from 'next';
import ClientLayout from './ClientLayout';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next asdfasdfasdfasdfasdfapp',
};


//git clone to  chekc tis working or not

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {




  return (
      <ClientLayout>
            {children}
      </ClientLayout>
    );
}
